batch_size: 2
workers: 0
nepoch: 100
model_name: vrcnet

load_model: /home/guests/miruna_gafencu/shape_completion/log/vrcnet_cd_debug_2024-02-08T12:09:38/best_cd_t_network.pth
num_partial_scans_per_mesh: 1
path_to_train_dataset: /home/polyaxon-data/data1/USShapeCompletion/MVP/completion/data/new_pipeline/4096/complete_pipeline/relativeScaling_alignedWIthSynthetic_newSplitting/dataset_verse_training.h5
path_to_val_dataset: /home/polyaxon-data/data1/USShapeCompletion/MVP/completion/data/new_pipeline/4096/complete_pipeline/relativeScaling_alignedWIthSynthetic_newSplitting/dataset_verse_validation.h5
#path_to_test_dataset: /home/polyaxon-data/data1/USShapeCompletion/MVP/completion/data/new_pipeline/4096/complete_pipeline/relativeScaling_alignedWIthSynthetic_newSplitting/dataset_verse_test.h5
path_to_test_dataset: /home/polyaxon-data/data1/USShapeCompletion/MVP/completion/patient_data/patient6_registered.h5
#path_to_test_dataset: /home/polyaxon-data/data1/USShapeCompletion/MVP/completion/patient_data/patient8_registered.h5
#name_folder_to_save_results: complete_pipeline_synthetic_data_with_emd
name_folder_to_save_results: complete_pipeline_patient6_with_emd
#name_folder_to_save_results: complete_pipeline_patient8

data_to_test: test
start_epoch: 0
num_points: 4096
work_dir: log/
flag: debug
loss: cd
manual_seed: null
use_mean_feature: False
step_interval_to_print: 500
epoch_interval_to_save: 1
epoch_interval_to_val: 1
varying_constant: 0.01, 0.1, 0.5, 1
varying_constant_epochs: 5, 15, 30

lr: 0.0001
lr_decay: True
lr_decay_interval: 40
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
lr_clip: 1.e-6
optimizer: Adam
weight_decay: 0
betas: 0.9, 0.999

layers: 1, 1, 1, 1
distribution_loss: KLD
knn_list: "16"
pk: 10
local_folding: True
points_label: True
num_coarse_raw: 2048
num_fps: 4096
num_coarse: 4096

apply_trafo: False
sigma: 0.005



# test
align: False
save_vis: False
eval_emd: True
